feat: Add Terragrunt and Tofu task scripts for managing infrastructure

diff --git a/.mise/tasks/terragrunt/stack/destroy b/.mise/tasks/terragrunt/stack/destroy
--- a/.mise/tasks/terragrunt/stack/destroy
+++ b/.mise/tasks/terragrunt/stack/destroy
@@ -4,6 +4,7 @@ set -e
 
 #USAGE arg "<target>" help="The target unit" default=""
 #USAGE flag "-d --dry-run" help="Show the commands without executing it"
+#USAGE flag "-a --auto-approve" help="Automatically approve the destroy action"
 
 STACKS_DIR="$MISE_CONFIG_ROOT/examples/terragrunt/stacks"
 
@@ -21,11 +22,15 @@ fi
 
 cd "$STACKS_DIR/$selected_stack"
 
-STACK_RUN_DESTROY_CMD="terragrunt stack run destroy"
+CMD="terragrunt stack run destroy"
+
+if [ "$usage_auto_approve" = "true" ]; then
+  CMD="$CMD --non-interactive"
+fi
 
 echo ""
 echo "🚀 Executing..."
-echo "   Commands: $STACK_RUN_DESTROY_CMD"
+echo "   Commands: $CMD"
 echo "   Working dir: $(pwd)"
 echo ""
 
@@ -34,4 +39,15 @@ if [ "$usage_dry_run" = "true" ]; then
   exit 0
 fi
 
-eval $STACK_RUN_DESTROY_CMD
+if [ "$usage_auto_approve" != "true" ]; then
+  echo "⚠️ Are you really sure to destroy the stack?"
+  read -p "Type 'do it baby' to confirm: " confirm
+
+  if [[ "$confirm" != "do it baby" ]]; then
+    echo ""
+    echo "Destroy aborted by user"
+    exit 1
+  fi
+fi
+
+eval $CMD
