chore: exit from tests with message if latest changes are not commited and pushed

diff --git a/.mise/tasks/test/all b/.mise/tasks/test/all
--- a/.mise/tasks/test/all
+++ b/.mise/tasks/test/all
@@ -76,6 +76,14 @@ function run_terragrunt_unit_tests() {
 
 # === TERRAGRUNT STACKS ===
 function run_terragrunt_stack_tests() {
+  # check latest changes to git are commited and pushed and fail with a message if not
+  GIT_STATUS=$(git status --porcelain)
+
+  if [ -n "$GIT_STATUS" ]; then
+    echo "❌ There are uncommitted changes in the repository. Please commit and push all changes before running stack tests."
+    exit 1
+  fi
+
   for STACK in "${STACKS[@]}"; do
     # mise --raw run terragrunt:stack:plan $STACK
     # sleep 1
